services:
  mysql:
    image: mysql
    container_name: mysql_container_rasmoo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: RASPLUS
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/data/db

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasmoo
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_container:/data/db

  redis:
    image: redis:4
    container_name: redis-rasplus
    ports:
      - "6379:6379"
    volumes:
      - redis_data_container:/data/redis

volumes:
  mysql_data_container:
  mongo_data_container:
  redis_data_container:
